"""
Adversarial test data for the Tatkal agent — generated by the pm-execution
stress-test pass (dummy-dataset skill).

Each block is pytest-parametrize-ready. The goal is NOT to assert today's
behaviour but to surface where parse_availability / evaluate_threshold /
passenger-fill make silent assumptions. Cases marked GAP currently have
no handling in the build.
"""

# ── 1. IRCTC availability badge strings ──────────────────────────────────────
# (raw_badge, expected_status_type, note)
# Feed into core.availability_parser.parse_availability
AVAILABILITY_BADGES = [
    # --- formats the parser is built for ---
    ("AVAILABLE-4",            "AVAILABLE",       "happy: 4 confirmed"),
    ("CURR_AVBL-3",            "CURR_AVBL",       "happy: 3 current"),
    ("RAC 7",                  "RAC",             "happy: rac 7"),
    ("GNWL 45/WL 30",          "GNWL",            "happy: wl_pos 30"),
    ("TQWL 3/WL 2",            "TQWL",            "happy: tatkal WL"),
    ("REGRET",                 "REGRET",          "not bookable"),
    ("TRAIN CANCELLED",        "TRAIN_CANCELLED", "not bookable"),

    # --- adversarial: spacing / case / punctuation ---
    ("available-4",            "AVAILABLE",       "lowercase — .upper() should save it"),
    ("AVAILABLE 4",            "AVAILABLE",       "space instead of dash"),
    ("GNWL45/WL30",            "GNWL",            "GAP? no spaces — regex findall still works"),
    ("  RAC  7  ",             "RAC",             "leading/trailing/internal whitespace"),
    ("CURR_AVBL",              "CURR_AVBL",       "no count — confirmed_count=None, still 'book'"),

    # --- adversarial: numeric edge values ---
    ("AVAILABLE-0",            "AVAILABLE",       "GAP: 0 seats but status AVAILABLE → evaluates to 'book'!"),
    ("AVAILABLE-0001",         "AVAILABLE",       "zero-padded count"),
    ("RAC 0",                  "RAC",             "rac 0 — rac_number falls back to 0"),
    ("WL 0",                   "WL",              "wl 0"),

    # --- adversarial: statuses the parser may not know ---
    ("CHART PREPARED",         "UNKNOWN",         "GAP: real IRCTC status, not handled → skip"),
    ("CHART NOT PREPARED",     "UNKNOWN",         "GAP: real status"),
    ("BOOKING CLOSED",         "UNKNOWN",         "GAP: window closed wording variant"),
    ("RUNNING STATUS",         "UNKNOWN",         "noise from wrong DOM cell"),
    ("CURR_AVBL-0008 (PT)",    "CURR_AVBL",       "premium-tatkal suffix in badge"),
    ("",                       "NOT_AVAILABLE",   "empty string"),
    ("हिंदी",                   "UNKNOWN",         "GAP: non-ASCII (Hindi) — known console-encoding crash"),
    ("AVAILABLE-4\n",          "AVAILABLE",       "trailing newline from text_content()"),
    ("AVAILABLE-4 | AVAILABLE-2", "AVAILABLE",    "GAP: two badges concatenated — takes first number only"),
]

# ── 2. Threshold-decision cases (status × thresholds → book/pause/skip) ───────
# (status_type, kwargs_for_result, thresholds_kwargs, expected_decision, note)
THRESHOLD_CASES = [
    ("AVAILABLE", {"confirmed_count": 4},  {}, "book",  "default: confirmed books"),
    ("AVAILABLE", {"confirmed_count": 0},  {}, "skip",  "FIXED: 0 seats now skips (was the AVAILABLE-0 bug)"),
    ("RAC",       {"rac_number": 5},       {}, "skip",  "default: RAC off"),
    ("RAC",       {"rac_number": 5},       {"max_rac": 10}, "book", "RAC within limit"),
    ("RAC",       {"rac_number": 9},       {"max_rac": 10}, "pause","borderline buffer"),
    ("TQWL",      {"wl_position": 2},      {"max_wl": 5, "allowed_wl_types": ["TQWL"]}, "book", "WL opted in"),
    ("GNWL",      {"wl_position": 2},      {"max_wl": 5}, "skip", "WL not in allowed_wl_types"),
]

# ── 3. Passenger edge cases ──────────────────────────────────────────────────
# (name, age, expected_issue)  — feed into core.models.Passenger
PASSENGER_EDGE = [
    ("Subrahmanyam Venkataraman", 33, "GAP: truncated to 15 chars SILENTLY — no warning, may break ID match"),
    ("A",                          5,  "single-char name — IRCTC min length?"),
    ("",                           30, "GAP: empty name accepted by dataclass"),
    ("José Ramírez",               40, "accented chars — IRCTC ASCII-only field?"),
    ("Baby Of Priya",              0,  "infant age 0 — separate IRCTC flow not modelled"),
    ("Test",                       -1, "GAP: negative age accepted (no validation)"),
    ("Test",                       150,"GAP: age 150 accepted (no upper bound)"),
    ("D'Souza",                    28, "apostrophe — selector/escaping risk in keyboard.type"),
]

# ── 4. Config permutations that break decision logic ─────────────────────────
# (description, config_overrides)
CONFIG_PERMUTATIONS = [
    ("AVAILABLE-1 but 2 passengers",
     {"availability": "AVAILABLE-1", "passenger_count": 2,
      "note": "GAP: confirmed_count never compared to passenger_count → partial booking"}),
    ("class_priority empty, travel_class set",
     {"class_priority": [], "travel_class": "SL",
      "note": "falls back to single-class path — OK"}),
    ("class_priority = [SL, 3A, 2A]",
     {"class_priority": ["SL", "3A", "2A"],
      "note": "3 serial availability reads inside window — timing risk (red-team #2)"}),
    ("book_only_if_confirmed=True, availability flips to WL after pay",
     {"book_only_if_confirmed": True,
      "note": "GAP: no post-payment guard — money taken for WL"}),
    ("quota=PREMIUM TATKAL",
     {"quota": "PREMIUM TATKAL",
      "note": "dynamic pricing not modelled — fare could exceed expectation"}),
]
